apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-tests-cron
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-tests-cron
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-tests-cron
subjects:
  - kind: ServiceAccount
    name: k8s-tests-cron
roleRef:
  kind: Role
  name: k8s-tests-cron
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-tests-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-tests-cron
  template:
    metadata:
      labels:
        app: k8s-tests-cron
    spec:
      serviceAccountName: k8s-tests-cron
      containers:
        - name: cron
          image: k8s-tests-cron:${IMAGE_TAG}
          imagePullPolicy: Never
